### PR TITLE
Syncfrrk8s211124

### PR DESCRIPTION
**Pull request by karampok**
Sync to upstream

### CODE REVIEW

**Comment by karampok** [comment]
@fedepaol @oribon test are failing with error
```
ERRO[2024-11-21T10:33:22Z] Some steps failed:                           
ERRO[2024-11-21T10:33:22Z] 
  * could not run steps: step frrk8s-e2e-metal failed: "frrk8s-e2e-metal" test steps failed: "frrk8s-e2e-metal" pod "frrk8s-e2e-metal-baremetalds-metallb-e2e-test" failed: could not watch pod: the pod ci-op-smqw238j/frrk8s-e2e-metal-baremetalds-metallb-e2e-test failed after 13m29s (failed containers: test): ContainerFailed one or more containers exited
```
Have you seen it before?

**Comment by karampok** [comment]
CI is failing because controller container cannot start, there is a complain about "health-probe-bind-address" which recently was removed.

```
omc -n metallb-system  logs -c controller frr-k8s-dgrvc
2024-11-21T10:27:31.963842746Z flag provided but not defined: -health-probe-bind-address
2024-11-21T10:27:31.964389116Z Usage of /frr-k8s:
2024-11-21T10:27:31.964573257Z   -always-block string
2024-11-21T10:27:31.964573257Z          a list of comma separated cidrs we need to always block
2024-11-21T10:27:31.964708058Z   -cert-dir string
2024-11-21T10:27:31.964708058Z          The directory where certs are stored (default "/tmp/k8s-webhook-server/serving-certs")
2024-11-21T10:27:31.964809065Z   -cert-service-name string
2024-11-21T10:27:31.964809065Z          The service name used to generate the TLS cert's hostname (default "frr-k8s-webhook-service")
2024-11-21T10:27:31.964941503Z   -disable-cert-rotation
2024-11-21T10:27:31.964941503Z          disable automatic generation and rotation of webhook TLS certificates/keys
2024-11-21T10:27:31.965068717Z   -kubeconfig string
2024-11-21T10:27:31.965068717Z          Paths to a kubeconfig. Only required if out-of-cluster.
2024-11-21T10:27:31.965162445Z   -log-level string
2024-11-21T10:27:31.965162445Z          log level. must be one of: [all, debug, info, warn, error, none] (default "info")
2024-11-21T10:27:31.965242635Z   -metrics-bind-address string
2024-11-21T10:27:31.965242635Z          The address the metric endpoint binds to. (default "127.0.0.1:7572")
2024-11-21T10:27:31.965312366Z   -namespace string
2024-11-21T10:27:31.965312366Z          The namespace this daemon is deployed in
2024-11-21T10:27:31.965378360Z   -node-name string
2024-11-21T10:27:31.965378360Z          The node this daemon is running on.
2024-11-21T10:27:31.965450580Z   -pprof-bind-address string
2024-11-21T10:27:31.965450580Z          The address the pprof endpoints bind to.
2024-11-21T10:27:31.965560218Z   -restart-on-rotator-secret-refresh
2024-11-21T10:27:31.965560218Z          Restart the pod when the rotator refreshes its cert.
2024-11-21T10:27:31.965663002Z   -webhook-mode string
2024-11-21T10:27:31.965663002Z          webhook mode: can be disabled or onlywebhook if we want the controller to act as webhook endpoint only (default "disabled")
2024-11-21T10:27:31.965753402Z   -zap-devel
2024-11-21T10:27:31.965753402Z          Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn). Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error) (default true)
2024-11-21T10:27:31.965842110Z   -zap-encoder value
2024-11-21T10:27:31.965842110Z          Zap log encoding (one of 'json' or 'console')
2024-11-21T10:27:31.965989598Z   -zap-log-level value
2024-11-21T10:27:31.965989598Z          Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
2024-11-21T10:27:31.966106875Z   -zap-stacktrace-level value
2024-11-21T10:27:31.966106875Z          Zap Level at and above which stacktraces are captured (one of 'info', 'error', 'panic').
2024-11-21T10:27:31.966198923Z   -zap-time-encoding value
2024-11-21T10:27:31.966198923Z          Zap time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'). Defaults to 'epoch'.
[I] kka@f-t14s ~> omc -n metallb-system describe logs frr-k8s-dgrvc
Invalid object type: logs
[I] kka@f-t14s ~ [1]> omc get pods -A|grep frr
metallb-system                                     frr-k8s-dgrvc                                                     5/6     CrashLoopBackOff   6          9m
metallb-system                                     frr-k8s-g5m5c                                                     5/6     CrashLoopBackOff   6          9m
metallb-system                                     frr-k8s-gp2tv                                                     5/6     CrashLoopBackOff   6          9m
metallb-system                                     frr-k8s-hjrn7                                                     5/6     CrashLoopBackOff   6          9m
metallb-system                                     frr-k8s-hpm7k                                                     5/6     CrashLoopBackOff   6          9m
metallb-system                                     frr-k8s-qhgcr                                                     5/6     CrashLoopBackOff   6          9m
metallb-system                                     frr-k8s-webhook-server-68c6c55cc6-fznhb                           0/1     CrashLoopBackOff   6          9m
```

Probably need to update the  manifest in the operator https://github.com/metallb/metallb-operator/blob/6abf1c69db0c974c0e2f9117da5e1996944a3106/bindata/deployment/helm/frr-k8s/templates/controller.yaml#L202 but I am not sure if that only needed.

**Comment by fedepaol** [comment]
Right path is:
- we do a frr-k8s release
- update metallb
- update the metallb-operator

Then we'll have a chicken - egg issue when bringing it d/s I guess, but we can override

**Pull request closed without merging**
